# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rating', '0002_moviecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
